# Generated by Django 5.1.5 on 2025-02-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('Guest', '0005_tbl_client_client_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_complaint',
            new_name='tbl_clientcomplaint',
        ),
    ]
