# Generated by Django 5.1.5 on 2025-02-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_rename_tbl_complaint_tbl_clientcomplaint'),
        ('Guest', '0005_tbl_client_client_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_clientcomplaint',
            old_name='client_id',
            new_name='client',
        ),
        migrations.CreateModel(
            name='tbl_clientfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=50)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_client')),
            ],
        ),
    ]
