# Generated by Django 5.1.5 on 2025-02-05 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_rename_client_id_tbl_clientcomplaint_client_and_more'),
        ('Guest', '0005_tbl_client_client_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=20)),
                ('work_details', models.CharField(max_length=100)),
                ('work_price', models.IntegerField()),
                ('work_docs', models.FileField(upload_to='Assets/Work')),
                ('work_date', models.DateField(auto_now_add=True)),
                ('work_completedate', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_client')),
            ],
        ),
    ]
