# Generated by Django 5.1.5 on 2025-02-06 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_tbl_work'),
        ('Guest', '0005_tbl_client_client_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('request_message', models.CharField(max_length=100)),
                ('request_file', models.FileField(upload_to='Assests/Freelancersrequestfile')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_freelancer')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.tbl_work')),
            ],
        ),
    ]
