# Generated by Django 5.1.5 on 2025-02-12 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_tbl_request'),
        ('Guest', '0005_tbl_client_client_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('client_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_from', to='Guest.tbl_client')),
                ('client_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_to', to='Guest.tbl_client')),
                ('freelancer_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_from', to='Guest.tbl_freelancer')),
                ('freelancer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_to', to='Guest.tbl_freelancer')),
            ],
        ),
    ]
