# Generated by Django 5.1.5 on 2025-02-13 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_tbl_chat'),
        ('Guest', '0005_tbl_client_client_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_content', models.CharField(max_length=20)),
                ('rating_value', models.IntegerField()),
                ('rating_datetime', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_client')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_freelancer')),
            ],
        ),
    ]
