# Generated by Django 5.1.5 on 2025-02-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_alter_tbl_chat_client_from_alter_tbl_chat_client_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='request_file',
            field=models.FileField(upload_to='Assets/Freelancersrequestfile/'),
        ),
    ]
