# Generated by Django 5.1.5 on 2025-01-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0005_tbl_client_client_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_subject', models.CharField(max_length=30)),
                ('comp_details', models.CharField(max_length=50)),
                ('comp_date', models.DateField(auto_now_add=True)),
                ('comp_reply', models.CharField(max_length=50)),
                ('comp_status', models.IntegerField(default=0)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_client')),
            ],
        ),
    ]
