# Generated by Django 5.1.5 on 2025-02-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_client_client_status_and_more'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_complaint',
            new_name='tbl_usercomplaint',
        ),
    ]
