# Generated by Django 5.1.5 on 2025-02-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_client_client_status_and_more'),
        ('User', '0003_tbl_ucomplaint_delete_tbl_usercomplaint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_ucomplaint',
            new_name='tbl_usercomplaint',
        ),
    ]
